apiVersion: v1
kind: Service

metadata:
  name: simple-html-canary-service
  namespace: canary-deploy

spec:
  type: NodePort

  selector:
    app: simple-html-app

  ports:
    - port: 80
      targetPort: 80
      nodePort: 30083