apiVersion: v1
kind: Service
metadata:
  name: simple-html-service
  namespace: production
spec:
  selector:
    app: simple-html-app
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30081