pipeline {

    agent any

    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
        IMAGE_NAME = "95337/simple-html-app"
    }

    stages {

        // GitLab Login
        stage('Clone Code') {
            steps {
                git branch: 'main',
                    credentialsId: 'gitlab-creds',
                    url: 'https://gitlab.com/jenkins-group2155922/docker-project.git'
            }
        }

        // Docker Version
        stage('docker-version') {
            steps {
                sh 'docker --version'
            }
        }

        // Docker Build
        stage('docker-build') {
            steps {
                sh 'docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .'
            }
        }

        // Docker Login
        stage('docker-login') {
            steps {

                withCredentials([usernamePassword(
                    credentialsId: 'docker_login',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {

                    sh '''
                        echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                    '''
                }
            }
        }

        // Docker Push
        stage('docker-push') {
            steps {
                sh 'docker push ${IMAGE_NAME}:${IMAGE_TAG}'
            }
        }

        // Docker Remove image
        stage('docker-image-remove'){
            steps{
                sh 'docker rmi ${IMAGE_NAME}:${IMAGE_TAG}'
                sh 'docker rmi nginx:alpine'
            }
        }
    }

    post {

        always {
            sh 'docker system prune -f'
        }

        success {
            echo "Pipeline run successfully"
        }

        failure {
            echo "Pipeline failed"
        }
    }
}